#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10

bspc config border_width         2
bspc config normal_border_color \#C2CBFF
bspc config active_border_color \#C2CBFF
bspc config focused_border_color \#B698DF
bspc config window_gap          12
bspc config top_padding 30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
